const mongoose = require('mongoose');

/**
 * Project Model
 *
 * Top-level project entity. A project groups multiple unit-type variants
 * (configurations) and individual unit inventory under one named project.
 *
 * Examples:
 *   "Lodha Park - Worli"    → 1 Project, 4 ProjectConfigurations, 240 ProjectUnits
 *   "Hiranandani Gardens"   → 1 Project, 6 ProjectConfigurations, 600 ProjectUnits
 *
 * Media (hero, gallery, master plan, brochure) is stored as Cloudinary
 * { url, publicId } pairs. publicId is required for deletion.
 *
 * Slug is auto-generated by the controller before create/update.
 */

const mediaSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    publicId: { type: String, required: true },
  },
  { _id: false }
);

const coordinatesSchema = new mongoose.Schema(
  {
    lat: { type: Number, default: null },
    lng: { type: Number, default: null },
  },
  { _id: false }
);

const projectSchema = new mongoose.Schema(
  {
    // ── Identity ────────────────────────────────────────────────────────
    builderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Builder',
      required: [true, 'Builder is required'],
    },
    name: {
      type: String,
      required: [true, 'Project name is required'],
      trim: true,
      maxlength: [200, 'Project name cannot exceed 200 characters'],
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    description: {
      type: String,
      trim: true,
      default: null,
    },
    shortDescription: {
      type: String,
      trim: true,
      maxlength: [400, 'Short description max 400 chars'],
      default: null,
    },

    // ── Classification ──────────────────────────────────────────────────
    projectType: {
      type: String,
      enum: {
        values: ['residential', 'commercial', 'mixed', 'plotting'],
        message: 'Invalid project type',
      },
      default: 'residential',
    },
    projectStatus: {
      type: String,
      enum: {
        values: ['new_launch', 'under_construction', 'ready_to_move'],
        message: 'Invalid project status',
      },
      default: 'new_launch',
    },
    listingStatus: {
      type: String,
      enum: {
        values: ['active', 'inactive', 'draft'],
        message: 'Invalid listing status',
      },
      default: 'draft',
    },

    // ── Location ────────────────────────────────────────────────────────
    location: {
      area: {
        type: String,
        required: [true, 'Area is required'],
        trim: true,
      },
      address: { type: String, trim: true, default: null },
      city: { type: String, default: 'Mumbai', trim: true },
      state: { type: String, default: 'Maharashtra', trim: true },
      pincode: { type: String, trim: true, default: null },
      coordinates: { type: coordinatesSchema, default: () => ({}) },
    },

    // ── Regulatory ──────────────────────────────────────────────────────
    reraNumber: { type: String, trim: true, default: null },
    reraUrl: { type: String, trim: true, default: null },

    // ── Dates ───────────────────────────────────────────────────────────
    possessionDate: { type: Date, default: null },
    launchDate: { type: Date, default: null },

    // ── Scale ───────────────────────────────────────────────────────────
    totalTowers: { type: Number, min: 0, default: null },
    totalFloors: { type: Number, min: 0, default: null },
    totalUnits:  { type: Number, min: 0, default: null },
    landArea:    { type: Number, min: 0, default: null }, // in sq ft

    // ── Price Summary (auto-computed or manually set) ───────────────────
    priceMin: { type: Number, min: 0, default: null },
    priceMax: { type: Number, min: 0, default: null },
    areaMin:  { type: Number, min: 0, default: null }, // carpet area in sq ft
    areaMax:  { type: Number, min: 0, default: null },

    // ── BHK Summary (e.g., ["1BHK", "2BHK", "3BHK"]) ──────────────────
    bhkSummary: { type: [String], default: [] },

    // ── Media ───────────────────────────────────────────────────────────
    heroImage:  { type: mediaSchema, default: null },
    gallery: {
      type: [mediaSchema],
      default: [],
      validate: {
        validator: (arr) => arr.length <= 20,
        message: 'Max 20 gallery images',
      },
    },
    masterPlan: { type: mediaSchema, default: null },
    brochure:   { type: mediaSchema, default: null },
    videoUrl:   { type: String, trim: true, default: null },

    // ── Flags ───────────────────────────────────────────────────────────
    isFeatured: { type: Boolean, default: false },

    // ── Contact ──────────────────────────────────────────────────────────
    contactPerson: { type: String, trim: true, default: null },
    contactPhone:  { type: String, trim: true, default: null },

    // ── Extended Pricing ─────────────────────────────────────────────────
    pricePerSqft:       { type: Number, default: null, min: 0 },
    maintenanceCharges: { type: String, trim: true, default: null },

    // ── Regulatory ───────────────────────────────────────────────────────
    reraVerified: { type: Boolean, default: false },

    // ── Lead Capture Settings ────────────────────────────────────────────
    enablePriceRequest:     { type: Boolean, default: true },
    enableCallback:         { type: Boolean, default: true },
    enableBrochureDownload: { type: Boolean, default: true },
    whatsappCtaEnabled:     { type: Boolean, default: true },
    enableSiteVisit:        { type: Boolean, default: true },

    // ── Amenities ───────────────────────────────────────────────────────
    amenities: { type: [String], default: [] },

    // ── SEO ─────────────────────────────────────────────────────────────
    seoTitle:       { type: String, trim: true, maxlength: [70, 'SEO title max 70 chars'], default: null },
    seoDescription: { type: String, trim: true, maxlength: [160, 'SEO description max 160 chars'], default: null },

    // ── Meta ────────────────────────────────────────────────────────────
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    views: { type: Number, default: 0, min: 0 },
    enquiryCount: { type: Number, default: 0, min: 0 },
  },
  { timestamps: true, versionKey: false }
);

// ── Indexes ──────────────────────────────────────────────────────────────
projectSchema.index({ builderId: 1 });
projectSchema.index({ 'location.area': 1 });
projectSchema.index({ listingStatus: 1 });
projectSchema.index({ projectStatus: 1 });
projectSchema.index({ isFeatured: 1 });
projectSchema.index({ priceMin: 1, priceMax: 1 });
projectSchema.index({ createdAt: -1 });
projectSchema.index({ listingStatus: 1, projectStatus: 1, 'location.area': 1 });
projectSchema.index({ listingStatus: 1, isFeatured: 1, createdAt: -1 });

module.exports = mongoose.model('Project', projectSchema);
